apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: "development"
  APP_DEBUG: "true"
  APP_CONFIG_FILE: "/etc/app/config.json"
  config.json: |
    {
      "database": {
        "host": "db-service",
        "port": 5432,
        "name": "appdb"
      },
      "cache": {
        "enabled": true,
        "ttl": 300
      }
    }
