apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: app
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo 'Environment variables:' && env | grep APP_ && echo 'Secret values:' && echo DB_USERNAME=$DB_USERNAME && echo DB_PASSWORD=$DB_PASSWORD && sleep 3600",
        ]
      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_DEBUG
        - name: APP_CONFIG_FILE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_CONFIG_FILE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
      volumeMounts:
        - name: config-volume
          mountPath: /etc/app
  volumes:
    - name: config-volume
      configMap:
        name: app-config
        items:
          - key: config.json
            path: config.json
