alloy:
  configMap:
    create: false
    name: alloy-config

extraVolumes:
  - name: varlogpods
    hostPath:
      path: /var/log/pods
  - name: varlogcontainers
    hostPath:
      path: /var/log/containers

extraVolumeMounts:
  - name: varlogpods
    mountPath: /var/log/pods
  - name: varlogcontainers
    mountPath: /var/log/containers
