apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-credentials
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: app-credentials
  data:
    - secretKey: username
      remoteRef:
        key: app/config
        property: username
    - secretKey: password
      remoteRef:
        key: app/config
        property: password
