# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodic-back
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: periodic-backup
              image: busybox
              args:
                [
                  "/bin/sh",
                  "-c",
                  "date; echo Hello from the Kubernetes cluster",
                ]
          restartPolicy: OnFailure
---

